;; ;madhu 250816 mininmal bindings to support the gficl imlib2 loader
;; Extracted from a file Generated by :claw at Mon May 26 09:16:37
;; 2025 +0530 ~/cl/extern/cl-claw-imlib2/gen/bindings/

(uiop:define-package "CLAW-CXX-IMLIB2" (:use))
(uiop:define-package :claw-cxx-imlib2-bindings~pristine (:use :cl))
(common-lisp:in-package :claw-cxx-imlib2-bindings~pristine)

(cffi:defcenum (claw-cxx-imlib2::|C:@EA@IMLIB-LOAD-ERROR| :unsigned-int)
  "/usr/include/Imlib2.h:2919:9"
  (:load-error-none 0)
  (:load-error-file-does-not-exist 1)
  (:load-error-file-is-directory 2)
  (:load-error-permission-denied-to-read 3)
  (:load-error-no-loader-for-file-format 4)
  (:load-error-path-too-long 5)
  (:load-error-path-component-non-existant 6)
  (:load-error-path-component-not-directory 7)
  (:load-error-path-points-outside-address-space 8)
  (:load-error-too-many-symbolic-links 9)
  (:load-error-out-of-memory 10)
  (:load-error-out-of-file-descriptors 11)
  (:load-error-permission-denied-to-write 12)
  (:load-error-out-of-disk-space 13)
  (:load-error-unknown 14)
  (:load-error-image-read 15)
  (:load-error-image-frame 16))

(cffi:defctype claw-cxx-imlib2::uint32-t :unsigned-int)

(cffi:defctype claw-cxx-imlib2::image (:pointer :void))


(cffi:defctype claw-cxx-imlib2::load-error
               claw-cxx-imlib2::|C:@EA@IMLIB-LOAD-ERROR|)

(cffi:defcfun ("imlib_load_image_with_errno_return"
               claw-cxx-imlib2::load-image-with-errno-return)
    claw-cxx-imlib2::image
  (claw-cxx-imlib2::file :string)
  (claw-cxx-imlib2::error-return (:pointer :int)))

(cffi:defctype claw-cxx-imlib2::load-error
               claw-cxx-imlib2::|C:@EA@IMLIB-LOAD-ERROR|)

(cffi:defcfun ("imlib_strerror" claw-cxx-imlib2::strerror)
    :string
  (claw-cxx-imlib2::err :int))

(cffi:defctype claw-cxx-imlib2::context (:pointer :void))

(cffi:defcfun ("imlib_context_set_image" claw-cxx-imlib2::context-set-image)
    :void
  (claw-cxx-imlib2::image claw-cxx-imlib2::image))

(cffi:defcfun ("imlib_image_get_height" claw-cxx-imlib2::image-get-height)
    :int)

(cffi:defcfun ("imlib_image_get_width" claw-cxx-imlib2::image-get-width)
    :int)

(cffi:defcfun ("imlib_image_get_data" claw-cxx-imlib2::image-get-data)
    (:pointer claw-cxx-imlib2::uint32-t))

(cffi:defcfun ("imlib_context_get" claw-cxx-imlib2::context-get)
    claw-cxx-imlib2::context)

(cffi:defcfun ("imlib_context_free" claw-cxx-imlib2::context-free)
    :void
  (claw-cxx-imlib2::context claw-cxx-imlib2::context))


(cffi:defcfun ("imlib_free_image" claw-cxx-imlib2::free-image)
    :void)


;;; ----------------------------------------------------------------------
;;;
;;; Exports
;;;

(eval-when (:load-toplevel :compile-toplevel :execute)
  (export 'claw-cxx-imlib2::|C:@EA@IMLIB-LOAD-ERROR| "CLAW-CXX-IMLIB2")
  (export 'claw-cxx-imlib2::load-error "CLAW-CXX-IMLIB2")
  (export 'claw-cxx-imlib2::load-image-with-errno-return "CLAW-CXX-IMLIB2")
  (export 'claw-cxx-imlib2::strerror "CLAW-CXX-IMLIB2")
  (export 'claw-cxx-imlib2::context "CLAW-CXX-IMLIB2")
  (export 'claw-cxx-imlib2::context-set-image "CLAW-CXX-IMLIB2")
  (export 'claw-cxx-imlib2::image-get-height "CLAW-CXX-IMLIB2")
  (export 'claw-cxx-imlib2::image-get-width "CLAW-CXX-IMLIB2")
  (export 'claw-cxx-imlib2::image-get-data "CLAW-CXX-IMLIB2")
  (export 'claw-cxx-imlib2::context-get "CLAW-CXX-IMLIB2")
  (export 'claw-cxx-imlib2::context-free "CLAW-CXX-IMLIB2")
  (export 'claw-cxx-imlib2::free-image "CLAW-CXX-IMLIB2"))


;;; ----------------------------------------------------------------------
;;;
;;; Shared lib. find-foreign-library in enometh/cffi
;;;

;; #+nil
(eval-when (:load-toplevel :compile-toplevel :execute)
(unless (cffi:find-foreign-library "Imlib2")
  (cffi:load-foreign-library "libImlib2.so")))

#+nil
(cffi:foreign-symbol-pointer "imlib_context_set_image")


;;; ----------------------------------------------------------------------
;;;
;;;
;;;

;; (user::package-add-nicknames "CLAW-CXX-IMLIB2" "IMLIB")
(eval-when (:load-toplevel :compile-toplevel :execute)
(let ((pkg "CLAW-CXX-IMLIB2")
      (nicknames '("IMLIB")))
  (rename-package (find-package pkg)
		  (package-name pkg)
		  (union nicknames (package-nicknames pkg) :test #'string=))))


